[project]
name = "neva-edu-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.18.0",
    "beautifulsoup4>=4.13.3",
    "dateparser>=1.2.1",
    "pydantic-settings>=2.8.1",
]
